import styles from './issue-0.module.scss'

export default function FavoriteWaterEssay() {
  return (
  <div className={styles.body}>
    <div>It's said that Thales believed the earth rests on water. He formed this hypothesis while watching cargo transported in and out of the port of Miletus. Water appeared permanent, immutable, and substantial when contrasted with the transience of earth.</div>
    <div>And so I proceeded to imagine an earth rested on water.</div>
    <div>Tainan, the city I live in, is Taiwan's oldest city and was the capital during the Qing dynasty. Being a harbor city, Tainan was used as a transit port for the Dutch East India Company until it was seized by the Chinese in 1662. As immigrants from China flooded into Tainan, it became clear that the promise of affluence came at the price of erratic weather and frequent natural disasters. Torrential rain and scorching summers threatened the livelihood of fishermen, traders, and sailors, so temples were erected to "消災祈福," which loosely translates to "warding calamity while bringing good fortune."</div>
    <div>In 1716, a wealthy merchant built Tsuí sian kiong (水仙宮）on Tainan's harbor to pray for safe passage at sea. Merchant ships were often lost at sea while braving the tumultuous waters separating China from Taiwan. Tsuí sian kiong was dedicated to Tsuí Sian Zun Wang（水仙尊王), five water gods deified from humans who solved water crises in ancient China. Not only did the temple become a religious sanctuary, it was a business center for three of the biggest trade companies in Taiwan, a marketplace for food, and an arena for political activity. Events and shows were also hosted at the temple during the holidays. It became the center of Tainan's west area, operating as a de facto city hall.</div>
    <div>As land development projects dictated shifts in Tainan's landscape, Tsuí sian kiong was no longer situated by the water during the Japanese occupation. During the Meiji era, two-thirds of the temple was taken apart by the Japanese and many artifacts were stolen or auctioned off. It was subsequently used as a bomb shelter during World War II and eventually partially reconstructed during Taiwan's retrocession era. Today, Tsuí sian kiong is a third of its original size and stands at the background of a popular fresh market. Its name has taken rank not as a historical or religious site but the subject of countless blog posts about surrounding food stalls. From the sidewalk, the temple is indiscernible, obscured by rows of stalls in a tented area. The stalls have been organized so that a straight pathway leading up to the temple is theatrically kept clear of produce, fish, meat, and dried goods and lit up by the skylight above. At the end of the tunnel where the tented area ends, the scent of raw food momentarily dissipates as the incense bowl in front of Tsuí sian kiong comes into view. The corridors of its 300 sq ft space are filled with cardboard boxes, unused signs, various plastic packaging, and pieces of broken down furniture. Not far from the Qing dynasty stone drums, rows of pastries are being cooled off on stainless steel trolleys in anticipation of the evening crowd. To the left of the temple, steam is emanating from pots of boiling water at a fifty-year-old noodle shop seeing lines out the door. Men and women stroll the parameters of the market, occasionally leaning closer to the red fluorescent lights to catch a better glimpse. Outside the market, tourists are seen galavanting the streets of food, looking for a line to get behind.</div>
    <div>Taking this sight in, I can't help but feel that this incarnation of Tsuí sian kiong might not be far from what it was in its heyday. Tsuí sian kiong was not singular or significant for being a temple built to pray for safe passage at sea. What made it monumental was that it was an anchor for Tainan, and such a legacy lives on, albeit in a different form. The area around Tsuí sian kiong continues to be the liveliest part of the city, and it continues to support the livelihood of hundreds of people. As Kevin McCloud once said on Grand Designs, "I think it's possible to remove every last detail from an old place and still retain its magic.”</div>
    <div>Water has the power to instill life into something that otherwise would've been an insignificant blip in time, but it also has the power to destroy all that’s standing. The temple wouldn’t have been built without a fear of water, yet it is due to the temple’s access to water that made it a force through which Tainan flourished from. Tsuí sian kiong transcends its place in history as a reminder of the paradox of water as both giver and taker. Today, the temple’s spirits have extended beyond the confines of its physical form.</div>
    <div>The earth is rested on water not because water is the heavier of the two but because water acts as constant reinforcement for earth. The ebbs and flows of water is what gives us the experience of change and difference.</div>
    <div>It is only due to the permanence of water that we’re given the opportunity to be impermanent.</div>
    <span>References</span>
    <span>王孝廉，水與水神，三民出版社一九九二年九月。</span>
    <span>姜義鎮，臺灣的鄉土神明，協和51，臺原出版社一九九五年四月。</span>
    <span>黃秋月建築師事務所研究，台南市第三級古蹟水仙宮調查研究與修護計劃 ，民88出版社二零零零年。</span>
    <span>黃靜宜， 王明雪，台南歷史散步（下），遠流出版社一九九五年七月。</span>
  </div>)
}